openapi: 3.0.1
info:
  title: Cube Codes Share Repository
  description: Allows to upload a cube-codes-ide app state and share it
  contact:
    email: info@cube.codes
  version: 1.0.0
paths:
  /appStates:
    post:
      summary: Add a new app state to the repository
      operationId: addAppState
      requestBody:
        description: App state that is added to the repository
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppState'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadSuccess'
        400:
          description: Client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /appStates/{id}:
    get:
      summary: Gets an app state from the repository
      operationId: getAppState
      parameters:
        - name: id
          in: path
          description: app state id
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppState'
        400:
          description: Client error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/S3Error'
components:
  schemas:
    UploadSuccess:
      type: object
      properties:
        url:
          type: string
    Error:
      type: object
      properties:
        message:
          type: string
    S3Error: {}
    CubeSpecification:
      type: object
      properties:
        edgeLength:
          type: integer
          format: int32
    CubeSolutionCondition:
      type: object
      properties:
        type:
          type: integer
          format: int32
    CubeHistory:
      type: object
      properties:
        initialState:
          type: string
        entries:
          type: array
          items:
            type: string
        currentPosition:
          type: integer
          format: int32
    Editor:
      type: object
      properties:
        code:
          type: string
    AutomaticAction:
      type: object
      properties:
        type:
          type: string
          enum:
          - none
          - programCodeRun
          - programCodeRunFast
          - historyStepAhead
          - historyStepBack
          - historyPlayAhead
          - historyPlayBack
    AppState:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        cubeSpec:
          $ref: '#/components/schemas/CubeSpecification'
        cubeSolutionCondition:
          $ref: '#/components/schemas/CubeSolutionCondition'
        cubeHistory:
          $ref: '#/components/schemas/CubeHistory'
        editor:
          $ref: '#/components/schemas/Editor'
        automaticAction:
          $ref: '#/components/schemas/AutomaticAction'
